apiVersion: v1
kind: Service
metadata:
  name: checkout-api
  namespace: ai-war-room-demo
  labels:
    app: checkout-api
spec:
  type: ClusterIP
  selector:
    app: checkout-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
